FROM openjdk:8-jre-alpine
COPY target/dodgydrivers-1.0-jar-with-dependencies.jar /dodgydrivers-1.0-jar-with-dependencies.jar
CMD ["/usr/bin/java", "-jar", "/dodgydrivers-1.0-jar-with-dependencies.jar", "localhost"]