FROM openjdk:11.0.8-jre
COPY target/dodgydrivers-1.0-jar-with-dependencies.jar /service.dodgydrivers-1.0-jar-with-dependencies.jar
CMD java -jar /service.dodgydrivers-1.0-jar-with-dependencies.jar ${SERVER_HOST}
